common:
  time_sync_en: false

preprocess:
  lidar_type: 2                # 1->Livox, 2->Velodyne, 3->Ouster, 4->Hesai, 5->Robosense, 6->LivoxPointCloud2
  scan_line: 32
  blind: 4
  time_scale: 1e-3

mapping:
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  det_range: 100.0
  extrinsic_est_en: true
  extrinsic_T: [ 0, 0, 0.28 ]
  extrinsic_R: [ 1, 0, 0,
                 0, 1, 0,
                 0, 0, 1 ]

output:
  path_en: false
  dense_en: false
  path_save_en: true

pcd_save:
  pcd_save_en: true
  interval: -1

feature_extract_enable: false
point_filter_num: 6
max_iteration: 3
filter_size_surf: 0.5
filter_size_map: 0.5
cube_side_length: 1000

ivox_grid_resolution: 0.5
ivox_nearby_type: 18             # 6, 18, 26
esti_plane_threshold: 0.1
